#!/usr/bin/env python3
"""Generate softphone/SIP provisioning from the 7AY carrier snapshot.

This bridge consumes `carrier_bridge.py` output and emits:
  - generated Asterisk PJSIP endpoints
  - generated dialplan routes
  - a JSON provisioning view for softphone apps

It is intended for devnet call testing over Wi-Fi or local IP connectivity.
It does not touch iPhone baseband provisioning or native iOS carrier bundles.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import time
from pathlib import Path
from typing import Any


ACTIVE_STATUSES = {"Activated", "Recovered"}


def load_json(path: str | Path) -> Any:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def wait_for_snapshot(path: Path, interval: int) -> dict[str, Any]:
    """Wait until the carrier snapshot exists and contains valid JSON."""
    announced = False
    while True:
        try:
            return load_json(path)
        except FileNotFoundError:
            if not announced:
                print(f"Waiting for carrier snapshot at {path} ...")
                announced = True
            time.sleep(max(interval, 1))
        except json.JSONDecodeError:
            if not announced:
                print(f"Waiting for valid carrier snapshot JSON at {path} ...")
                announced = True
            time.sleep(max(interval, 1))


def normalize_subscribers(snapshot: dict[str, Any]) -> list[dict[str, Any]]:
    subscribers = snapshot.get("subscribers", [])
    return [entry for entry in subscribers if isinstance(entry, dict)]


def is_bridge_eligible(subscriber: dict[str, Any]) -> bool:
    status = subscriber.get("status")
    provisioning_state = subscriber.get("provisioning_state")
    return status in ACTIVE_STATUSES and provisioning_state != "Failed"


def load_trunk_config(path: str | None) -> dict[str, Any] | None:
    """Load SIP trunk configuration from JSON file."""
    if not path:
        return None
    try:
        return load_json(path)
    except (FileNotFoundError, json.JSONDecodeError) as exc:
        print(f"Warning: could not load trunk config from {path}: {exc}")
        return None


def render_pjsip(
    subscribers: list[dict[str, Any]],
    realm: str,
    trunk: dict[str, Any] | None = None,
    webrtc: bool = False,
) -> str:
    lines = [
        "; Auto-generated by carrier_softphone_bridge.py",
        f"; generated_at={int(time.time())}",
        "",
    ]

    for subscriber in subscribers:
        catalog = subscriber.get("catalog", {})
        dial_number = catalog.get("dial_number")
        username = catalog.get("sip_username")
        password = catalog.get("sip_password")
        status = subscriber.get("status")

        if not is_bridge_eligible(subscriber) or not dial_number or not username or not password:
            continue

        lines.extend(
            [
                f"[{username}]",
                "type=endpoint",
                "context=seveny-devnet",
                "disallow=all",
                "allow=ulaw,alaw",
                f"auth={username}-auth",
                f"aors={username}",
                "direct_media=no",
                "rewrite_contact=yes",
                "rtp_symmetric=yes",
                "force_rport=yes",
                f"callerid=\"{catalog.get('display_name', dial_number)}\" <{dial_number}>",
                "",
                f"[{username}-auth]",
                "type=auth",
                "auth_type=userpass",
                f"username={username}",
                f"password={password}",
                f"realm={realm}",
                "",
                f"[{username}]",
                "type=aor",
                "max_contacts=2",
                "remove_existing=yes",
                "",
            ]
        )

        # WebRTC-compatible endpoint variant
        if webrtc:
            lines.extend(
                [
                    f"[{username}-ws]",
                    "type=endpoint",
                    "webrtc=yes",
                    "context=seveny-devnet",
                    "disallow=all",
                    "allow=opus,ulaw",
                    f"auth={username}-auth",
                    f"aors={username}",
                    "direct_media=no",
                    "rewrite_contact=yes",
                    "rtp_symmetric=yes",
                    "force_rport=yes",
                    f"callerid=\"{catalog.get('display_name', dial_number)}\" <{dial_number}>",
                    "",
                ]
            )

    # Trunk registration stanza
    if trunk:
        registrar = trunk.get("registrar", "")
        trunk_user = trunk.get("username", "")
        trunk_pass = trunk.get("password", "")
        transport = trunk.get("transport", "udp")
        context_in = trunk.get("context_in", "seveny-pstn-in")

        if registrar and trunk_user:
            lines.extend(
                [
                    "; --- SIP Trunk Registration ---",
                    "",
                    "[trunk-auth]",
                    "type=auth",
                    "auth_type=userpass",
                    f"username={trunk_user}",
                    f"password={trunk_pass}",
                    "",
                    "[trunk-aor]",
                    "type=aor",
                    f"contact=sip:{registrar}",
                    "qualify_frequency=60",
                    "",
                    "[trunk-registration]",
                    "type=registration",
                    f"transport=transport-{transport}",
                    "outbound_auth=trunk-auth",
                    f"server_uri=sip:{registrar}",
                    f"client_uri=sip:{trunk_user}@{registrar}",
                    "retry_interval=60",
                    "",
                    "[trunk-endpoint]",
                    "type=endpoint",
                    f"transport=transport-{transport}",
                    f"context={context_in}",
                    "disallow=all",
                    "allow=ulaw,alaw,opus",
                    "outbound_auth=trunk-auth",
                    "aors=trunk-aor",
                    "direct_media=no",
                    "rewrite_contact=yes",
                    "rtp_symmetric=yes",
                    "force_rport=yes",
                    f"from_domain={registrar}",
                    "",
                ]
            )

            outbound_proxy = trunk.get("outbound_proxy", "")
            if outbound_proxy:
                # Insert before the last empty line
                lines.insert(-1, f"outbound_proxy=sip:{outbound_proxy}")

    return "\n".join(lines).rstrip() + "\n"


def render_extensions(
    subscribers: list[dict[str, Any]],
    trunk: dict[str, Any] | None = None,
) -> str:
    lines = [
        "; Auto-generated by carrier_softphone_bridge.py",
        "",
        "[seveny-devnet]",
    ]

    active = []
    did_map: dict[str, str] = {}  # e164 -> sip_username

    for subscriber in subscribers:
        catalog = subscriber.get("catalog", {})
        dial_number = catalog.get("dial_number")
        username = catalog.get("sip_username")
        status = subscriber.get("status")
        pstn_did = catalog.get("pstn_did")

        if is_bridge_eligible(subscriber) and dial_number and username:
            active.append((dial_number, username))
            lines.extend(
                [
                    f"exten => {dial_number},1,NoOp(7AY inbound call for {dial_number})",
                    f" same => n,Dial(PJSIP/{username},30)",
                    " same => n,Voicemail(${EXTEN}@default,u)",
                    " same => n,Hangup()",
                    "",
                ]
            )
            if pstn_did:
                # Strip + prefix for dialplan matching
                did_clean = pstn_did.lstrip("+")
                did_map[did_clean] = username

    if active:
        lines.extend(
            [
                "; Simple ring group for quick smoke tests",
                "exten => 7999,1,NoOp(7AY broadcast ring)",
                " same => n,Dial("
                + "&".join(f"PJSIP/{username}" for _, username in active)
                + ",20)",
                " same => n,Hangup()",
                "",
            ]
        )

    # Outbound PSTN routing (only when trunk is configured)
    if trunk:
        context_out = trunk.get("context_out", "seveny-pstn-out")
        lines.extend(
            [
                "; Outbound PSTN via trunk",
                f"include => {context_out}",
                "",
                f"[{context_out}]",
                "; NANP 10-digit",
                "exten => _NXXNXXXXXX,1,NoOp(7AY PSTN outbound: ${EXTEN})",
                " same => n,Dial(PJSIP/${EXTEN}@trunk-endpoint,60)",
                " same => n,Hangup()",
                "",
                "; NANP 1+10-digit",
                "exten => _1NXXNXXXXXX,1,NoOp(7AY PSTN outbound: ${EXTEN})",
                " same => n,Dial(PJSIP/${EXTEN}@trunk-endpoint,60)",
                " same => n,Hangup()",
                "",
                "; Full E.164 (+ stripped)",
                "exten => _X.,1,NoOp(7AY PSTN outbound E.164: ${EXTEN})",
                " same => n,Dial(PJSIP/${EXTEN}@trunk-endpoint,60)",
                " same => n,Hangup()",
                "",
            ]
        )

    # Inbound DID routing
    if did_map:
        context_in = trunk.get("context_in", "seveny-pstn-in") if trunk else "seveny-pstn-in"
        lines.extend(
            [
                f"[{context_in}]",
                "; Inbound DID -> on-chain subscriber routing",
            ]
        )
        for did, username in sorted(did_map.items()):
            lines.extend(
                [
                    f"exten => {did},1,NoOp(7AY PSTN inbound DID {did})",
                    f" same => n,Dial(PJSIP/{username},30)",
                    " same => n,Voicemail(${EXTEN}@default,u)",
                    " same => n,Hangup()",
                    "",
                ]
            )

    return "\n".join(lines).rstrip() + "\n"


def build_provisioning(snapshot: dict[str, Any], sip_domain: str, sip_port: int) -> dict[str, Any]:
    entries = []
    for subscriber in normalize_subscribers(snapshot):
        catalog = subscriber.get("catalog", {})
        if not is_bridge_eligible(subscriber):
            continue
        if not catalog.get("sip_username") or not catalog.get("sip_password"):
            continue
        entries.append(
            {
                "number_id": subscriber.get("number_id"),
                "dial_number": catalog.get("dial_number"),
                "display_name": catalog.get("display_name", catalog.get("dial_number")),
                "sip_username": catalog.get("sip_username"),
                "sip_password": catalog.get("sip_password"),
                "sip_domain": sip_domain,
                "sip_port": sip_port,
                "transport": "udp",
                "status": subscriber.get("status"),
                "activation_epoch": subscriber.get("activation_epoch"),
                "owner": subscriber.get("owner"),
                "device_id": subscriber.get("device_id"),
                "region_id": subscriber.get("region_id"),
                "provisioning_state": subscriber.get("provisioning_state", "None"),
                "provisioning_receipt": subscriber.get("provisioning_receipt"),
                "pstn_did": catalog.get("pstn_did"),
            }
        )

    return {
        "generated_at": int(time.time()),
        "summary": {
            "softphone_subscriber_count": len(entries),
        },
        "subscribers": entries,
    }


def write_outputs(
    output_dir: Path,
    provisioning: dict[str, Any],
    pjsip_conf: str,
    extensions_conf: str,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "subscribers.softphone.json").write_text(
        json.dumps(provisioning, indent=2) + "\n",
        encoding="utf-8",
    )
    (output_dir / "pjsip.generated.conf").write_text(pjsip_conf, encoding="utf-8")
    (output_dir / "extensions.generated.conf").write_text(
        extensions_conf, encoding="utf-8"
    )


def config_checksum(pjsip_conf: str, extensions_conf: str) -> str:
    """SHA-256 checksum of combined config output for change detection."""
    combined = (pjsip_conf + extensions_conf).encode("utf-8")
    return hashlib.sha256(combined).hexdigest()


def trigger_reload(method: str, container: str) -> None:
    """Trigger Asterisk config reload via CLI or ARI."""
    if method == "ari":
        try:
            import urllib.request
            url = "http://localhost:8088/ari/asterisk/modules/res_pjsip"
            req = urllib.request.Request(url, method="PUT")
            req.add_header("Authorization", "Basic c2V2ZW55LWRldm5ldDo3YXktYXJpLWRldm5ldA==")
            urllib.request.urlopen(req, timeout=5)
            print("Asterisk reload triggered via ARI")
        except Exception as exc:
            print(f"ARI reload failed ({exc}), falling back to CLI")
            trigger_reload("cli", container)
    else:
        try:
            subprocess.run(
                ["docker", "exec", container, "asterisk", "-rx", "pjsip reload"],
                capture_output=True, timeout=10, check=False,
            )
            subprocess.run(
                ["docker", "exec", container, "asterisk", "-rx", "dialplan reload"],
                capture_output=True, timeout=10, check=False,
            )
            print("Asterisk reload triggered via CLI")
        except Exception as exc:
            print(f"CLI reload failed: {exc}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--snapshot",
        default="devnet/state/carrier-bridge.json",
        help="Carrier snapshot JSON produced by carrier_bridge.py.",
    )
    parser.add_argument(
        "--output-dir",
        default="devnet/telecom/generated",
        help="Generated provisioning/config directory.",
    )
    parser.add_argument(
        "--sip-domain",
        default="127.0.0.1",
        help="SIP domain or IP address used by the softphone.",
    )
    parser.add_argument(
        "--sip-port",
        type=int,
        default=5060,
        help="SIP UDP port exposed by the Asterisk devnet.",
    )
    parser.add_argument(
        "--realm",
        default="seveny-devnet",
        help="SIP auth realm.",
    )
    parser.add_argument(
        "--trunk-config",
        default=None,
        help="Path to SIP trunk config JSON for PSTN connectivity.",
    )
    parser.add_argument(
        "--webrtc",
        action="store_true",
        help="Generate WebRTC-compatible PJSIP endpoints.",
    )
    parser.add_argument(
        "--auto-reload",
        action="store_true",
        default=False,
        help="Reload Asterisk when generated config changes.",
    )
    parser.add_argument(
        "--reload-method",
        choices=["cli", "ari"],
        default="cli",
        help="Asterisk reload method (default: cli).",
    )
    parser.add_argument(
        "--reload-container",
        default="seveny-asterisk",
        help="Docker container name for CLI reload.",
    )
    parser.add_argument(
        "--watch",
        action="store_true",
        help="Regenerate continuously.",
    )
    parser.add_argument(
        "--interval",
        type=int,
        default=5,
        help="Watch interval in seconds.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    snapshot_path = Path(args.snapshot)
    output_dir = Path(args.output_dir)
    trunk = load_trunk_config(args.trunk_config)
    prev_checksum: str | None = None

    def run_once() -> None:
        nonlocal prev_checksum
        snapshot = wait_for_snapshot(snapshot_path, args.interval)
        subscribers = normalize_subscribers(snapshot)
        provisioning = build_provisioning(snapshot, args.sip_domain, args.sip_port)
        pjsip_conf = render_pjsip(
            subscribers, args.realm, trunk=trunk, webrtc=args.webrtc
        )
        extensions_conf = render_extensions(subscribers, trunk=trunk)
        write_outputs(output_dir, provisioning, pjsip_conf, extensions_conf)
        print(
            f"Wrote {provisioning['summary']['softphone_subscriber_count']} "
            f"softphone subscriber(s) into {output_dir}"
        )

        # Auto-reload on config change
        if args.auto_reload:
            checksum = config_checksum(pjsip_conf, extensions_conf)
            if prev_checksum is not None and checksum != prev_checksum:
                trigger_reload(args.reload_method, args.reload_container)
            prev_checksum = checksum

    run_once()
    if not args.watch:
        return 0

    while True:
        time.sleep(max(args.interval, 1))
        run_once()


if __name__ == "__main__":
    raise SystemExit(main())
